### PR TITLE
Add abstract and introduction

### PR DESCRIPTION
**Pull request by rubensworks**
This PR adds an abstract and introduction.
It outlines the scope and goals of this note, so it may be good to have a review on this before I continue writing the actual contents.

***
<a href="https://pr-preview.s3.amazonaws.com/rubensworks/json-ld-streaming/pull/1.html" title="Last updated on Mar 9, 2020, 3:17 PM UTC (28d9cae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-streaming/1/e2f57c3...rubensworks:28d9cae.html" title="Last updated on Mar 9, 2020, 3:17 PM UTC (28d9cae)">Diff</a>

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks for the feedback.

> Clearly, implementations must use libraries that preserve order for this to be effective.

Right, I will add a note on this.

> Note that serializations should always include @id, even if it is only used as a node for this object, otherwise and implementation will need to buffer in case it appears at the end of the object.

I may be misunderstanding what you mean. But how I see it, if no `@id` is detected before _any other properties_ are read, a processor can safely assume that no `@id` will ever occur, so a blank node can be created for the subject of this node. In this case, an `@id` is not required, right?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-03-06-json-ld#section3-1).

- `ACTION:  raise issue on exception/buffer in streaming. (Gregg Kellogg)`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.1. Streaming<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-streaming/pull/1">https://github.com/w3c/json-ld-streaming/pull/1</a><br/>
Rob Sanderson: rubensworks has done some work on the Streaming document recently. Where is that?<br/>
Rob Sanderson: <a href="https://pr-preview.s3.amazonaws.com/rubensworks/json-ld-streaming/pull/1.html">https://pr-preview.s3.amazonaws.com/rubensworks/json-ld-streaming/pull/1.html</a><br/>
Ruben Taelman: At the moment, the document changes a new “streaming document form” where the order is important.<br/>
Gregg Kellogg: .. In 2.3, a new profile is introduced, similar to other profiles for expanded and compacted.<br/>
Ruben Taelman: Section 3 describes the best order for receiving triples for a serializer to effectively create a document.<br/>
Gregg Kellogg: Section 4 discusses some tactics for processors.<br/>
Rob Sanderson: There’s a lot of good stuff in there.<br/>
Gregg Kellogg: One comment … should an object always have an <code>@id</code> … what if you don’t see one first?<br/>
… if you don’t see one first, then infer it’s a blank node<br/>
… my question is if it should always be present, so you’re less subjected to out of order keys<br/>
… if it appears in the wrong place, then you would have already emitted the triples<br/>
… is it okay if something is wrong to emit the bad data<br/>
… don’t think there’s any other key that really has that effect<br/>
Ruben Taelman: <a href="https://pr-preview.s3.amazonaws.com/rubensworks/json-ld-streaming/pull/1.html#streaming-deserialization">https://pr-preview.s3.amazonaws.com/rubensworks/json-ld-streaming/pull/1.html#streaming-deserialization</a><br/>
Ruben Taelman: The motivation was to allow streaming processors to buffer, in that case I mention that if a processor detects an out of order key it may through an error.<br/>
Rob Sanderson: You note that <code>@type</code> should come before <code>@id</code> where the value indicates a type-scoped context. That seems relevant, but you will already of encountered property-scoped contexts.<br/>
… It seems like a valuable observation that we might want to make more obvious.<br/>
… I usually see the order <code>@context,</code> <code>@id,</code> <code>@type,</code> but this would be different.<br/>
… Is the <code>@type</code> coming before <code>@id</code> important?<br/>
Ruben Taelman: I would say it’s important, as it can influence what <code>@id</code> is treated.<br/>
David I. Lehn: If you do see <code>@id</code> later, you could output a triple to say that the emitted blank node was equivalent to the <code>@id.</code><br/>
Ruben Taelman: I want to note that the processing is not entirely the same way my implementation works. In my case, if I don’t see <code>@id,</code> it will buffer. But that makes things a bit more complicated.<br/>
… If you can do it without buffering the implementation will be simpler.<br/>
Harold Solbrig: We make statements about things not being ordered, even though they’re not.<br/>
Gregg Kellogg: there’s two effects of ordering – json objects aren’t ordered, but in a serialization they are. So if some processes are to work, such as streaming, then they would need to be<br/>
… and secondly lists aren’t ordered (unless <code>@list)</code><br/>
… if the backing store doesn’t preserve order of unordered arrays, then the tests need to be for unordered sets<br/>
… reasonable for keeping object properties ordered for this to work<br/>
… should decide what to do in this case<br/>
Ruben Taelman: Perhaps section 4.1 we can add something about buffering rather than throwing an error.<br/>
Action #1: raise issue on exception/buffer in streaming. (Gregg Kellogg)<br/>
Rob Sanderson: I’ll be traveling next week, but I think bigbluehat is available, so there should be a meeting next week.<br/>
</details>

**Comment by rubensworks** [comment]
@gkellogg Is it ok if I merge this? Or should this be approved first during the weekly telco?

**Comment by gkellogg** [comment]
No, it’s a note, you’re acting under the groups authority. Any issues the group has can be handled as issues. You should use your own judgement for changes and give a reasonable time for feedback on PRs, as you did here.

**Pull request merged**
